### ISSUE TITLE
Does not connect to Classic network

### ISSUE THREAD

**Issue by ericsomdahl** [ethereumproject/pyethereum#1]

**Comment by whatisgravity** [comment]
If you are not sure, a good start is switching out the bootstrap nodes. It may even be best to migrate that issue from go-ethereum to volunteer since it is a broad topic.

**Comment by ericsomdahl** [comment]
I agree RE: the broad topics. I think these issues (including how to ignore block 1920000) might be good subjects for ECIP 1 and 2.

**Comment by whatisgravity** [comment]
Good points, if you do not have time to start drafts I can take over that task once time is available.

**Comment by ericsomdahl** [comment]
I will start on them tonight.  I don't know enough about the guts how it should work to do a proper write-up but I can get them started

**Comment by ericsomdahl** [comment]
I'm closing this issue out as not applicable.  After digging into the code I now know a bit better how pyethereum, pyethapp, and pydevp2p interact with each other.  Pyethereum doesn't have any of the p2p layer thus has no bearing on classic or HF networking.
