### ISSUE TITLE
Interest in continuing this project?

### ISSUE THREAD

**Issue by ericsomdahl** [ethereumproject/pyethereum#10]
There seems to be a general lack of interest in the python ethereum client codebase.  I have yet to hear about anyone demanding a functional python client for the Classic network.  The lack of demand for this product indicates that the (however minimal) effort spent is wasted.

Unless I get feedback to the contrary by 11 SEP 16 at 1200 EST, I am going to delete the pyethereum repo, along with other associated python repos in the Github project.

**Comment by realcodywburns** [comment]
I like the py repo because it is easy for everyone to read the code and understand what is going on with it.

**Comment by ericsomdahl** [comment]
Upon further review -- I have decided I'm willing to spend the time supporting this.  I started a project that is leveraging pydevp2p and pyethereum, and i have new appreciation for what they provide.  I'm closing this issue
