### ISSUE TITLE
Needs to ignore ChildDao code/block 1920000

### ISSUE THREAD

**Issue by ericsomdahl** [ethereumproject/pyethereum#2]

**Comment by whatsdis** [comment]
can you elaborate

**Comment by ericsomdahl** [comment]
This issue is a placeholder.  We will be starting an ECIP to flesh the logic of this out so that all classic impls can do the right thing

**Comment by rguiu** [comment]
This code seems to be here:
https://github.com/ethereumproject/pyethereum/blob/44dace9a2c638277a267d87d7091cf8393c21b9a/ethereum/blocks.py#L1184-L1186

But, I am still trying to familiarize with everything.

**Comment by realcodywburns** [comment]
From the original pull requests it looks like this one did the damage https://github.com/ethereum/pyethereum/pull/397

**Comment by ericsomdahl** [comment]
yep -- I think this is the extent of it.  So we need a few things:
1. undo the changes from the PR @realcodywburns linked
2. create a new test fixture in the **tests** repo that has the Classic version of block 1920000
3. update the tests so that more do not fail

Data for the new test fixture can be found in the ethereumj PR for fixing this same issue:  [PR3](https://github.com/ethereumproject/ethereumj/pull/3)

In my local build there are 3 tests that currently fail, the same as on the original **develop** branch.  @rguiu Are you seeing the same thing?

**Comment by ericsomdahl** [comment]
this issue was fixed with PR #7
