### ISSUE TITLE
Fork project Tests from Ethereum

### ISSUE THREAD

**Issue by rguiu** [ethereumproject/pyethereum#3]
https://github.com/ethereum/tests

It is refered as a module in .gitmodules, it should be forked and change the reference.

**Comment by ericsomdahl** [comment]
Done!  

See [tests](https://github.com/ethereumproject/tests)

**Comment by ericsomdahl** [comment]
oops --re-opening because I have not commited the .gitmodules reference

**Comment by ericsomdahl** [comment]
Fixed on **develop** by commit  
[7427c028d1315b90b52e14d6a72b2e223fd903bd](https://github.com/ethereumproject/pyethereum/commit/7427c028d1315b90b52e14d6a72b2e223fd903bd)

And I promise to be a good citizen and issue proper PRs
