### ISSUE TITLE
Naming conflict with original project

### ISSUE THREAD

**Issue by rguiu** [ethereumproject/pyethereum#8]
We may need to install under a different name to avoid conflicts. Ideas?

**Comment by whatisgravity** [comment]
When considering these changes make sure to consider that guides may be more difficult for novice users. 

Did you come to a conclusion on what to do on regarding this topic?

**Comment by ericsomdahl** [comment]
this issue was redundant with #6 so we've closed it.

we don't have a resolution yet but we are close
